all: RaceOrNot1 RaceOrNot2 RaceOrNot3
RaceOrNot1: RaceOrNot1.c
	gcc -o RaceOrNot1 -pthread RaceOrNot1.c
RaceOrNot2: RaceOrNot2.c
	gcc -o RaceOrNot2 -pthread RaceOrNot2.c
RaceOrNot3: RaceOrNot3.c
	gcc -o RaceOrNot3 -pthread RaceOrNot3.c
